name: Bug report
description: Report a defect in Virex behavior
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Clear description of the issue
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Minimal steps and code sample
    validations:
      required: true
  - type: textarea
    id: expected_actual
    attributes:
      label: Expected vs actual
      description: What you expected and what happened
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Flutter version, Dart version, platform
    validations:
      required: true
